#pragma once

#include "ast/allocation-ast.h"
#include "ast/assignment-ast.h"
#include "ast/binary-operator-ast.h"
#include "ast/block-ast.h"
#include "ast/expr-ast.h"
#include "ast/function-call-ast.h"
#include "ast/if-ast.h"
#include "ast/literal-ast.h"
#include "ast/read-ast.h"
#include "ast/return-ast.h"
#include "ast/statement-ast.h"
#include "ast/unary-operator-ast.h"
#include "ast/variable-ast.h"
#include "ast/write-ast.h"
